---
- name: Install libraries using apt
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
     - tmux
     - tree
     - zsh

- name: Change shell to ZSH
  sudo: true
  user: shell=/usr/bin/zsh name={{ ansible_ssh_user }}

