---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ansible
    - tmux
    - git

- name: Install cask packages
  homebrew_cask: name={{ item }} state=present
  with_items:
    - iterm2
    - alacritty
    - google-chrome
    - firefox
    - keepassxc
    - google-drive
    - docker
    - visual-studio-code
    - dbeaver-community
    - figma
    - jetbrains-toolbox
