---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ack
    - ansible
    - archey
    - aspell
    - atk
    - autoconf
    - autoenv
    - automake
    - bdw-gc
    - boost
    - brew-cask
    - tmux
    - ranger
    - git
    - zsh
    - wget
    - pyenv
    - pyenv-virtualenv
    - nvim

- name: Install cask packages
  homebrew_cask: name={{ item }} state=present
  with_items:
    - iterm2
    - google-chrome
    - firefox
    - keepassxc
    - google-drive
    - docker
    - visual-studio-code
    - dbeaver-community
